### ISSUE TITLE
Can TrackSomthing.py track different motion?

### ISSUE THREAD

**Issue by InckieUltra** [PKU-MoCCA/MuscleVAE#2]
Your work is amazing.
I tried to retarget a dance animation clip from lafan1 to the MuscleVAE model, and changed the animation path in Parameters and NNMmodel config. But the track process failed.
So can MuscleVAE track a new animation? Or did I do something wrong?

**Comment by InckieUltra** [comment]
It seems that blender rotate the model along global X.
Now the rotation problem is solved, but the skeleton limbs scales very long.
![屏幕截图 2024-10-10 164254](https://github.com/user-attachments/assets/72e515f1-cd21-4f70-ab7a-4cee633a3999)
I wonder how to properly retarget the bvh motion.
Thks very much.

**Comment by wangchek** [comment]
Hi @InckieUltra , thank you for your attention. The MuscleVAE engine do take into considerations of the translation of the BVH files. So if your offsets between joints are incompatible with the orignal ones which likes BVH files here `https://raw.githubusercontent.com/PKU-MoCCA/MuscleVAE/refs/heads/main/Data/ReferenceData/walk_run_jump/lafan_run.bvh`, the muscles will be treated wrongly. So please pay attention to the offsets beween joints. And make sure that the offsets are calculated in a local way.
